In [3]:
import sklearn
import sklearn.datasets as dt
import numpy as np
import numpy.random as rd
import matplotlib.pyplot as plt

In [4]:
IRIS = dt.load_iris()
IRIS_DATA = IRIS.data
IRIS_TARGETS = IRIS.target

print(f"IRIS data shape: {IRIS_DATA.shape}")
print(f"IRIS data (First three rows):")
print(*IRIS_DATA[0:3], sep="\n")

print(f"\nIRIS TARGET shape: {IRIS_TARGETS.shape}")
print(f"IRIS targets (First three rows): {IRIS_TARGETS[:3]}")

IRIS data shape: (150, 4)
IRIS data (First three rows):
[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]

IRIS TARGET shape: (150,)
IRIS targets (First three rows): [0 0 0]


In [5]:
CLASSIFICATION_ARRAY = [[-8, 1, 5, -4, -1],
                        [20, 0, -9, 4, -9],
                        [-25, 0, 3, 0, 11]]

### Transpose data array and insert ones for easy matrix multiplication

In [11]:
IRIS_T = IRIS_DATA.T
print(f"Transposed data shape: {IRIS_T.shape}")
print(f"Same three examples, now transposed:")
print(*IRIS_T[:,:3], sep="\n")

ONES_ARRAY = np.ones(150)
print(f"\nOnes array shape: {ONES_ARRAY.shape}")
print(f"Ones array (First 3 elements):")
print(ONES_ARRAY[:3])

IRIS_FINAL = np.vstack((ONES_ARRAY, IRIS_T))
print(f"\nFINAL ARRAY shape: {IRIS_FINAL.shape}")
print(f"Vstack result (First 3 points):")
print(IRIS_FINAL[:,:3])

Transposed data shape: (4, 150)
Same three examples, now transposed:
[5.1 4.9 4.7]
[3.5 3.  3.2]
[1.4 1.4 1.3]
[0.2 0.2 0.2]

Ones array shape: (150,)
Ones array (First 3 elements):
[1. 1. 1.]

FINAL ARRAY shape: (5, 150)
Vstack result (First 3 points):
[[1.  1.  1. ]
 [5.1 4.9 4.7]
 [3.5 3.  3.2]
 [1.4 1.4 1.3]
 [0.2 0.2 0.2]]


### Dot product

In [12]:
RESULTS = CLASSIFICATION_ARRAY@IRIS_FINAL

print(f"RESULTS shape {RESULTS.shape}")
print(f"RESULTS (first 3 examples):")
print(RESULTS[:,:3])

RESULTS shape (3, 150)
RESULTS (first 3 examples):
[[  8.8   6.1   7.3]
 [ -7.7  -3.2  -5.4]
 [-12.3 -13.8 -13.2]]


In [14]:
IRIS_PREDICTION = np.argmax(RESULTS, axis=0)

print(f"PREDICTION shape {IRIS_PREDICTION.shape}")
print(f"PREDICTION (first 3 examples):")
print(IRIS_PREDICTION[:3])

PREDICTION shape (150,)
PREDICTION (first 3 examples):
[0 0 0]


In [20]:
print(f"num of predicted 0s that should be 0s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 0] == 0)}")
print(f"num of predicted 1s that should be 0s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 0] == 1)}")
print(f"num of predicted 2s that should be 0s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 0] == 2)}")
print()
print(f"num of predicted 0s that should be 1s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 1] == 0)}")
print(f"num of predicted 1s that should be 1s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 1] == 1)}")
print(f"num of predicted 2s that should be 1s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 1] == 2)}")
print()
print(f"num of predicted 0s that should be 2s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 2] == 0)}")
print(f"num of predicted 1s that should be 2s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 2] == 1)}")
print(f"num of predicted 2s that should be 2s: {np.sum(IRIS_PREDICTION[IRIS_TARGETS == 2] == 2)}")

num of predicted 0s that should be 0s: 50
num of predicted 1s that should be 0s: 0
num of predicted 2s that should be 0s: 0

num of predicted 0s that should be 1s: 0
num of predicted 1s that should be 1s: 32
num of predicted 2s that should be 1s: 18

num of predicted 0s that should be 2s: 0
num of predicted 1s that should be 2s: 5
num of predicted 2s that should be 2s: 45


In [22]:
from sklearn.metrics import confusion_matrix

cf = confusion_matrix(IRIS_TARGETS, IRIS_PREDICTION)

print(f"Confusion Matrix:")
print(*cf, sep="\n")

Confusion Matrix:
[50  0  0]
[ 0 32 18]
[ 0  5 45]
