In [479]:
import sklearn
import sklearn.datasets as dt
import numpy as np
import numpy.random as rd
import matplotlib.pyplot as plt

In [480]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

Load Datasets

In [481]:
IRIS = dt.load_iris()
print(f"IRIS: {IRIS.data.shape}")
WINE = dt.load_wine()
print(f"WINE: {WINE.data.shape}")

IRIS: (150, 4)
WINE: (178, 13)


Split data into training and testing arrays

In [482]:
DATASET = WINE
TEST_SIZE = 0.3
STRATIFY = True
SHUFFLE = True
MAX_ITER = 10000

In [483]:
train_data, test_data, train_data_t, test_data_t = train_test_split(DATASET.data, DATASET.target, test_size=TEST_SIZE, shuffle=SHUFFLE, stratify=DATASET.target if STRATIFY else None)

Train the logistic regressor

In [484]:
logreg = LogisticRegression(max_iter=MAX_ITER).fit(train_data, train_data_t)

In [485]:
print(f'Percentagem de acertos: {(logreg.score(test_data, test_data_t)*100):.2f}')

Percentagem de acertos: 98.15


Calculate the confusion matrix

In [486]:
predictions = logreg.predict(test_data)
cf = confusion_matrix(test_data_t, predictions)
print(f'Confusion matrix:')
print(*cf, sep="\n")
print(f'\nNúmero total de erros: {np.sum(test_data_t != predictions)}')

Confusion matrix:
[18  0  0]
[ 0 20  1]
[ 0  0 15]

Número total de erros: 1


## Geração de Variaveis Aleatórias

In [493]:
X = rd.randn(3, 5)
print(X)
print(f"Norma: {np.sqrt(np.sum(X**2, axis=0))}")

[[-1.03469696 -1.00490217 -0.29046003 -0.4173907   0.88238836]
 [-0.21524882 -3.32586505 -0.07859279  0.93034309  0.18197655]
 [-0.75657633 -1.40026348 -0.51638562  0.27535075 -1.838095  ]]
Norma: [1.2997452  3.74592372 0.59766041 1.05620609 2.0470266 ]
