In [66]:
import numpy as np
import numpy.random as rd
import matplotlib.pyplot as plt
import sklearn.datasets as dt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, precision_recall_curve
import pickle

In [67]:
with open("A51597_Q001_data.p", 'rb') as file:
    dataset: dict = pickle.loads(file.read())
    
data = np.array(dataset.get('dados'))
target = np.array(dataset.get('trueClass'))

with open("A51597_Ficha1_Respostas.p", 'rb') as file:
    respostas = pickle.loads(file.read())
    
print(respostas.get('Q002'))

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


In [68]:
X = np.array([[-4, -4, -5, -4, 6, 6, 4], [-2, -1, -2, -2, -4, -4, -2]])
X = X.T

In [69]:
class0 = X[:4]
class1 = X[4:]

cov = np.cov(class1.T)
media = np.mean(class1, axis=0)
result = np.dot(cov, media)
result = np.round(result, 2)
print(result)

respostas.get('Q002')[0] = np.array([0, 0, 0, 1])

[ 11.56 -11.56]


In [71]:
media0 = np.mean(class0, axis=0)
media1 = media

dist_manh = np.sum(np.abs(media0 - media1))
dist_manh = np.round(dist_manh, 2)

print(dist_manh)

cos_sim= np.dot(media0, media1) / (np.linalg.norm(media0) * np.linalg.norm(media1))
cos_dist= 1 - cos_sim

print(np.round(cos_dist, 2))

respostas.get('Q002')[1] = np.array([1, 0, 0, 0])

11.17
1.58


In [72]:
print(respostas.get('Q001'))
print(respostas.get('Q002'))

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [ ]:
bytes = pickle.dumps(respostas)

with open('A51597_Ficha1_Respostas_2.p', 'wb') as file:
    file.write(bytes)
    
print(pickle.loads(open('A51597_Ficha1_Respostas_2.p', 'rb').read()))

{'Q001': array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]]), 'Q002': array([[0., 0., 0., 1.],
       [1., 0., 0., 0.]]), 'nome': 'Rui Manuel Branco Cardoso Rodrigues Ferreira', 'numero': 'A51597'}
